export const blogsData = [
  {
    id: 1,
    title: "html",
    body: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Non distinctio consequatur ex velit amet, delectus sit beatae placeat voluptate labore quis, deleniti consectetur dicta reiciendis qui aperiam error excepturi architecto facilis vitae exercitationem dolorem! Doloremque velit necessitatibus tenetur ab voluptas placeat sequi, similique ex incidunt, odio consectetur nisi, adipisci molestias doloribus. Repellat corrupti esse quis beatae placeat. Expedita autem rem sapiente, id molestiae blanditiis, dolores distinctio velit amet voluptatibus assumenda. Iusto voluptatibus possimus impedit amet voluptate repellat saepe recusandae suscipit quasi cupiditate deleniti, ea tempora delectus rerum ullam, nostrum est ut dignissimos in aperiam? Velit natus consequuntur, odio neque dolor quam error labore laudantium amet ut, porro quasi temporibus doloremque! Necessitatibus, qui dolore. Provident amet eos voluptatibus numquam a cupiditate iure ad corrupti consequatur, soluta, quis error nesciunt aspernatur consequuntur. Error, praesentium nisi et officia consectetur modi laborum distinctio, quaerat maiores soluta delectus ut magnam autem earum aperiam voluptas dolor similique dolores, labore sunt corrupti incidunt voluptatem. Ipsum id quos nihil necessitatibus reiciendis alias magni eveniet voluptates voluptatem tenetur eligendi soluta explicabo ducimus temporibus ut perspiciatis, iusto facere! Recusandae officia dolorum voluptatem sunt deserunt neque deleniti. Nobis quam facere necessitatibus enim tempore repellat, aliquam deleniti, quas, adipisci a magnam officia?",
  },
  {
    id: 2,
    title: "css",
    body: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Non distinctio consequatur ex velit amet, delectus sit beatae placeat voluptate labore quis, deleniti consectetur dicta reiciendis qui aperiam error excepturi architecto facilis vitae exercitationem dolorem! Doloremque velit necessitatibus tenetur ab voluptas placeat sequi, similique ex incidunt, odio consectetur nisi, adipisci molestias doloribus. Repellat corrupti esse quis beatae placeat. Expedita autem rem sapiente, id molestiae blanditiis, dolores distinctio velit amet voluptatibus assumenda. Iusto voluptatibus possimus impedit amet voluptate repellat saepe recusandae suscipit quasi cupiditate deleniti, ea tempora delectus rerum ullam, nostrum est ut dignissimos in aperiam? Velit natus consequuntur, odio neque dolor quam error labore laudantium amet ut, porro quasi temporibus doloremque! Necessitatibus, qui dolore. Provident amet eos voluptatibus numquam a cupiditate iure ad corrupti consequatur, soluta, quis error nesciunt aspernatur consequuntur. Error, praesentium nisi et officia consectetur modi laborum distinctio, quaerat maiores soluta delectus ut magnam autem earum aperiam voluptas dolor similique dolores, labore sunt corrupti incidunt voluptatem. Ipsum id quos nihil necessitatibus reiciendis alias magni eveniet voluptates voluptatem tenetur eligendi soluta explicabo ducimus temporibus ut perspiciatis, iusto facere! Recusandae officia dolorum voluptatem sunt deserunt neque deleniti. Nobis quam facere necessitatibus enim tempore repellat, aliquam deleniti, quas, adipisci a magnam officia?",
  },
  {
    id: 3,
    title: "react",
    body: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Non distinctio consequatur ex velit amet, delectus sit beatae placeat voluptate labore quis, deleniti consectetur dicta reiciendis qui aperiam error excepturi architecto facilis vitae exercitationem dolorem! Doloremque velit necessitatibus tenetur ab voluptas placeat sequi, similique ex incidunt, odio consectetur nisi, adipisci molestias doloribus. Repellat corrupti esse quis beatae placeat. Expedita autem rem sapiente, id molestiae blanditiis, dolores distinctio velit amet voluptatibus assumenda. Iusto voluptatibus possimus impedit amet voluptate repellat saepe recusandae suscipit quasi cupiditate deleniti, ea tempora delectus rerum ullam, nostrum est ut dignissimos in aperiam? Velit natus consequuntur, odio neque dolor quam error labore laudantium amet ut, porro quasi temporibus doloremque! Necessitatibus, qui dolore. Provident amet eos voluptatibus numquam a cupiditate iure ad corrupti consequatur, soluta, quis error nesciunt aspernatur consequuntur. Error, praesentium nisi et officia consectetur modi laborum distinctio, quaerat maiores soluta delectus ut magnam autem earum aperiam voluptas dolor similique dolores, labore sunt corrupti incidunt voluptatem. Ipsum id quos nihil necessitatibus reiciendis alias magni eveniet voluptates voluptatem tenetur eligendi soluta explicabo ducimus temporibus ut perspiciatis, iusto facere! Recusandae officia dolorum voluptatem sunt deserunt neque deleniti. Nobis quam facere necessitatibus enim tempore repellat, aliquam deleniti, quas, adipisci a magnam officia?",
  },
  {
    id: 4,
    title: "javaScript",
    body: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Non distinctio consequatur ex velit amet, delectus sit beatae placeat voluptate labore quis, deleniti consectetur dicta reiciendis qui aperiam error excepturi architecto facilis vitae exercitationem dolorem! Doloremque velit necessitatibus tenetur ab voluptas placeat sequi, similique ex incidunt, odio consectetur nisi, adipisci molestias doloribus. Repellat corrupti esse quis beatae placeat. Expedita autem rem sapiente, id molestiae blanditiis, dolores distinctio velit amet voluptatibus assumenda. Iusto voluptatibus possimus impedit amet voluptate repellat saepe recusandae suscipit quasi cupiditate deleniti, ea tempora delectus rerum ullam, nostrum est ut dignissimos in aperiam? Velit natus consequuntur, odio neque dolor quam error labore laudantium amet ut, porro quasi temporibus doloremque! Necessitatibus, qui dolore. Provident amet eos voluptatibus numquam a cupiditate iure ad corrupti consequatur, soluta, quis error nesciunt aspernatur consequuntur. Error, praesentium nisi et officia consectetur modi laborum distinctio, quaerat maiores soluta delectus ut magnam autem earum aperiam voluptas dolor similique dolores, labore sunt corrupti incidunt voluptatem. Ipsum id quos nihil necessitatibus reiciendis alias magni eveniet voluptates voluptatem tenetur eligendi soluta explicabo ducimus temporibus ut perspiciatis, iusto facere! Recusandae officia dolorum voluptatem sunt deserunt neque deleniti. Nobis quam facere necessitatibus enim tempore repellat, aliquam deleniti, quas, adipisci a magnam officia?",
  },
  {
    id: 5,
    title: "paython",
    body: " Lorem ipsum dolor sit amet consectetur adipisicing elit. Non distinctio consequatur ex velit amet, delectus sit beatae placeat voluptate labore quis, deleniti consectetur dicta reiciendis qui aperiam error excepturi architecto facilis vitae exercitationem dolorem! Doloremque velit necessitatibus tenetur ab voluptas placeat sequi, similique ex incidunt, odio consectetur nisi, adipisci molestias doloribus. Repellat corrupti esse quis beatae placeat. Expedita autem rem sapiente, id molestiae blanditiis, dolores distinctio velit amet voluptatibus assumenda. Iusto voluptatibus possimus impedit amet voluptate repellat saepe recusandae suscipit quasi cupiditate deleniti, ea tempora delectus rerum ullam, nostrum est ut dignissimos in aperiam? Velit natus consequuntur, odio neque dolor quam error labore laudantium amet ut, porro quasi temporibus doloremque! Necessitatibus, qui dolore. Provident amet eos voluptatibus numquam a cupiditate iure ad corrupti consequatur, soluta, quis error nesciunt aspernatur consequuntur. Error, praesentium nisi et officia consectetur modi laborum distinctio, quaerat maiores soluta delectus ut magnam autem earum aperiam voluptas dolor similique dolores, labore sunt corrupti incidunt voluptatem. Ipsum id quos nihil necessitatibus reiciendis alias magni eveniet voluptates voluptatem tenetur eligendi soluta explicabo ducimus temporibus ut perspiciatis, iusto facere! Recusandae officia dolorum voluptatem sunt deserunt neque deleniti. Nobis quam facere necessitatibus enim tempore repellat, aliquam deleniti, quas, adipisci a magnam officia?",
  },
];
